# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "This lane builds app"
  lane :build do
    xcbuild
  end

  desc "This lane runs unit tests"
  lane :tests do
    run_tests(scheme: "WarStatTests")
  end

  desc "This lane builds and tests app"
  lane :buildAndTest do
    build
    tests
  end

  desc "This lane creates IPA file"
  lane :createIPA do
    gym(
      project: "WarStat.xcodeproj",
      configuration: "Debug",
      scheme: "WarStat",
      clean: true,
      output_directory: "build",
      output_name: "wstat.ipa"
    )
  end
end
