name: Xcode - Build and Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  iOS_DESTINATION: "platform=iOS Simulator,OS=latest,name=iPhone 15"

jobs:
  WarStatBuild:
    name: Build and Test scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: Build WarStat
      #   run: |
      #     set -o pipefail && xcodebuild build \
      #       -derivedDataPath ../Build/DerivedData \
      #       -clonedSourcePackagesDirPath ../Build/ClonedSources \
      #       -scheme WarStat \
      #       -sdk iphonesimulator \
      #       -destination "$iOS_DESTINATION" 2>&1
      - name: Test WarStat
        run: |
          run: xcodebuild -project WarStat.xcodeproj -scheme "WarStat" -parallel-testing-enabled NO -destination "platform=iOS Simulator,OS=latest,name=iPhone 15" test \
